// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniCds.Infrastructure.Persistence;

#nullable disable

namespace MiniCds.Infrastructure.Migrations
{
    [DbContext(typeof(CdsDbContext))]
    [Migration("20260909052130_AddSampleMethodRawSignalPeak")]
    partial class AddSampleMethodRawSignalPeak
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MiniCds.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("ActorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrevHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SignatureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("MiniCds.Domain.Entities.ElectronicSignature", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuditEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LinkedEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkedEntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuditEntryId");

                    b.HasIndex("UserId");

                    b.HasIndex("LinkedEntityType", "LinkedEntityId");

                    b.ToTable("electronic_signatures", (string)null);
                });

            modelBuilder.Entity("MiniCds.Domain.Entities.Method", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("methods", (string)null);
                });

            modelBuilder.Entity("MiniCds.Domain.Entities.Peak", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApexIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metrics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SampleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("VoidedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("VoidedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VoidedReason")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SampleId");

                    b.HasIndex("VoidedByUserId");

                    b.ToTable("peaks", (string)null);
                });

            modelBuilder.Entity("MiniCds.Domain.Entities.RawSignal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Points")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("SampleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SampleRateHz")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SampleId");

                    b.ToTable("raw_signals", (string)null);
                });

            modelBuilder.Entity("MiniCds.Domain.Entities.Sample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MethodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VoidedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("VoidedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VoidedReason")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MethodId");

                    b.HasIndex("Status");

                    b.HasIndex("VoidedByUserId");

                    b.ToTable("samples", (string)null);
                });

            modelBuilder.Entity("MiniCds.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MiniCds.Domain.Entities.AuditEntry", b =>
                {
                    b.HasOne("MiniCds.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniCds.Domain.Entities.ElectronicSignature", b =>
                {
                    b.HasOne("MiniCds.Domain.Entities.AuditEntry", null)
                        .WithMany()
                        .HasForeignKey("AuditEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniCds.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniCds.Domain.Entities.Method", b =>
                {
                    b.HasOne("MiniCds.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("MiniCds.Domain.Entities.Peak", b =>
                {
                    b.HasOne("MiniCds.Domain.Entities.Sample", "Sample")
                        .WithMany("Peaks")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniCds.Domain.Entities.User", "VoidedBy")
                        .WithMany()
                        .HasForeignKey("VoidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sample");

                    b.Navigation("VoidedBy");
                });

            modelBuilder.Entity("MiniCds.Domain.Entities.RawSignal", b =>
                {
                    b.HasOne("MiniCds.Domain.Entities.Sample", "Sample")
                        .WithMany("RawSignals")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("MiniCds.Domain.Entities.Sample", b =>
                {
                    b.HasOne("MiniCds.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniCds.Domain.Entities.Method", "Method")
                        .WithMany("Samples")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniCds.Domain.Entities.User", "VoidedBy")
                        .WithMany()
                        .HasForeignKey("VoidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("Method");

                    b.Navigation("VoidedBy");
                });

            modelBuilder.Entity("MiniCds.Domain.Entities.Method", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("MiniCds.Domain.Entities.Sample", b =>
                {
                    b.Navigation("Peaks");

                    b.Navigation("RawSignals");
                });
#pragma warning restore 612, 618
        }
    }
}
